### ISSUE TITLE
Error using load Unable to read file './data/FLICKR-25K.mat'. No such file or directory.

### ISSUE THREAD

**Issue by yulijun1234** [jiangqy/DCMH-CVPR2017#5]
您好！　请问FLICKR-25K.mat数据可以分享下吗，我是新手，或者可以教下我怎么处理吗

**Comment by jiangqy** [comment]
FYI.

https://github.com/jiangqy/DCMH-CVPR2017/tree/master/DCMH_matlab/DCMH_matlab

Best regards.
Qing-Yuan.

----- Original Message -----
From: yulijun1234
[mailto:notifications@github.com]
To: jiangqy/DCMH-CVPR2017
[mailto:DCMH-CVPR2017@noreply.github.com]
Cc: Subscribed
[mailto:subscribed@noreply.github.com]
Sent: Thu, 08 Nov 2018 09:37:38
+0000
Subject: [jiangqy/DCMH-CVPR2017] Error using load Unable to read file
'./data/FLICKR-25K.mat'. No such file or directory. (#5)


> 您好！　请问FLICKR-25K.mat数据可以分享下吗，我是新手，或者可以教下我怎么处理吗

--
> 
You are receiving this because you are subscribed to this thread.
Reply to
> this email directly or view it on
> GitHub:
https://github.com/jiangqy/DCMH-CVPR2017/issues/5
